### PR TITLE
Gh 126 fix albam version in error report

### PR DESCRIPTION
**Pull request by Brachi**
Include correct version in error report (right now that would be 0.4.0.dev11) and redact user home.
Also say how to read the console in unexpected errors.

### CODE REVIEW

**Comment by Brachi** [comment]
@HenryOfCarim  could you please test that the user home is redacted in Windows?

**Comment by HenryOfCarim** [comment]
@Brachi Well, the result is strange, it doesn't show the report as it did before, in the console for errors like this
image
For other errors it shows the trace with the username
```Traceback (most recent call last):
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\albam\vfs.py", line 270, in execute
    w.write(vfile.get_bytes())
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\albam\vfs.py", line 67, in get_bytes
    accessor = self.get_accessor()
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\albam\vfs.py", line 76, in get_accessor
    root = vfs.file_list[self.tree_node.root_id]
KeyError: 'bpy_prop_collection[key]: key "" not found'```

**Comment by Brachi** [comment]
@HenryOfCarim  Can you try to force an unexpected error message and check the traceback in the console?

Per #118 , you can force by simply removing a material and then exporting.

> For other errors it shows the trace with the username

Is this from an unexpected error as well? or a "check" that failed?

**Comment by HenryOfCarim** [comment]
@Brachi  For this error it worked as expected
image

**Review by HenryOfCarim — APPROVED** [review]

**Pull request merged**
